# Generated by Django 4.2.28 on 2026-02-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='products.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='dest_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfers', to='products.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_movements', to='products.warehouse'),
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
